namespace program;

attribute nodeId;

enum Flag: uint32(bit_flags) {
  // When a program buffer reaches it maximum size, it gets split into segments.
  // Each bit flag represents the order of the current buffer.
  // Therefore, there can be only be up to four segments.
  FirstSegment,
  SecondSegment,
  ThirdSegment,
  ForthSegment,
}

// --- Nodes ---
struct NodeValue {
  value: uint64(nodeId);         // Node Address
  type: uint32;                  // TypeDef Address
  flags: uint32;                 // ValueFlag
}

union NodeUnion {
  IndexedNode,        // If node contains array or requires id
  BinaryNode,         // If node only requires 2 node values and no id
  UnaryNode,          // If node only required 1 node value and no id
}

table IndexedNode {
  id: uint32;
  fields: [NodeValue];
}

table BinaryNode {
  left:NodeValue;
  right:NodeValue;
}

table UnaryNode {
  value:NodeValue;      // Any flags stored outside of the node content
}

table Node {
  id: uint64(nodeId);     // unique node id
  opcode: uint32;         // opcode of node
  parent: uint64(nodeId); // parent node id
  next: uint64(nodeId);   // next sibling id
  flags: uint32;          // contains the node type and miscellanous flags
  node: NodeUnion;        // actual node contents
}

table StringEntry {
  key: uint32(key);
  value: string;
}
