include "../program.fbs";

namespace golang;

enum Opcode : uint32 {
  // --- Declarations ---
  Package = 0,        // package <identifier> | IndexedNode
  Import = 1,         // import "<path>" | IndexedNode
  ImportValue,        // <name> "<url>"   | BinaryNode
  Const,              // const <name> = <expr> | IndexedNode
  ConstValue,         // <name> = <expr> | BinaryNode
  Var,                // var <name> = <expr> | IndexedNode
  VarValue,           // <name> = <expr> | BinaryNode
  Type,               // type <name> <type> | IndexedNode
  Func,               // func <name>(...) { ... } | IndexedNode

  // --- Control Flow ---
  If,                 // if <cond> { ... } | IndexedNode
  For,                // <init>; <cond>; <post> | IndexedNode
  ForRange,           // for <forRange> { ... } | IndexedNode
  Switch,             // switch <expr> { ... } | IndexedNode
  Select,             // select { ... } | IndexedNode
  Case,               // case <expr>: <...> | IndexedNode
  Default,            // default: <...> | IndexedNode

  // --- Operators ---
  Add,                // <a> + <b> | BinaryNode
  Sub,                // <a> - <b> | BinaryNode
  Mul,                // <a> * <b> | BinaryNode
  Div,                // <a> / <b> | BinaryNode
  Mod,                // <a> % <b> | BinaryNode
  Inc,                // <a>++ | UnaryNode
  Dec,                // <a>-- | UnaryNode
  Assign,             // <a> = <b> | BinaryNode
  AddAssign,          // <a> += <b> | BinaryNode
  SubAssign,          // <a> -= <b> | BinaryNode
  MulAssign,          // <a> *= <b> | BinaryNode
  DivAssign,          // <a> += <b> | BinaryNode
  ModAssign,          // <a> %= <b> | BinaryNode
  BitAndAssign,       // <a> &= <b> | BinaryNode
  BitOrAssign,        // <a> |= <b> | BinaryNode
  BitXorAssign,       // <a> ^= <b> | BinaryNode
  BitClearAssign,     // <a> &^= <b> | BinaryNode
  LeftShiftAssign,    // <a> <<= <b> | BinaryNode
  RightShiftAssign,   // <a> >>= <b> | BinaryNode
  Equal,              // <a> == <b> | BinaryNode
  NotEqual,           // <a> != <b> | BinaryNode
  Less,               // <a> < <b> | BinaryNode
  LessEqual,          // <a> <= <b> | BinaryNode
  Greater,            // <a> > <b> | BinaryNode
  GreaterEqual,       // <a> >= <b> | BinaryNode
  And,                // <a> && <b> | BinaryNode
  Or,                 // <a> || <b> | BinaryNode
  Not,                // !<a> | UnaryNode
  BitAnd,             // <a> & <b> | BinaryNode
  BitOr,              // <a> | <b> | BinaryNode
  BitXor,             // <a> ^ <b> | BinaryNode
  BitClear,           // <a> ^& <b> | BinaryNode
  LeftShift,          // <a> << <b> | BinaryNode
  RightShift,         // <a> >> <b> | BinaryNode

  // --- Channels ---
  Send,               // ch <- val | BinaryNode
  Receive,            // <-ch | UnaryNode

  // --- Pointers & References ---
  AddrOf,             // &var | UnaryNode
  Deref,              // *ptr | UnaryNode

  // --- Functions & Calls ---
  Call,               // func(...) | IndexedNode
  Return,             // return <expr> | IndexedNode
  Defer,              // defer <call> | UnaryNode
  GoRoutine,          // go <call> | UnaryNode

  // --- Composite Types ---
  Map,                // map[keyType]valType{...} | IndexedNode
  Array,              // [n]type{...} | IndexedNode
  Chan,               // chan type | UnaryNode
  Constructor,        // []int{1, 2, 3} | IndexedNode

  // --- Error Handling ---
  Panic,              // panic(<expr>) | UnaryNode
  Recover,            // recover() | NONE

  // --- Built-in & Special ---
  Make,               // make(...) | IndexedNode
  New,                // new(type) | UnaryNode
  Len,                // len(...) | UnaryNode
  Cap,                // cap(...) | UnaryNode
  Append,             // append(...) | IndexedNode
  Copy,               // copy(dst, src) | BinaryNode
  Close,              // close(ch) | UnaryNode
  Complex,            // complex(...) | BinaryNode
  Real,               // real(...) | UnaryNode
  Imag,               // imag(...) | UnaryNode
  Print,              // print(...) | IndexedNode
  Println             // println(...) | IndexedNode
}

// --- Go Types ---
enum Kind : uint32 {
  nil = 0,          //
  int = 1,          //
  int8,             //
  int16,            //
  int32,            //
  int64,            //
  uint8,            //
  uint16,           //
  uint32,           //
  uint64,           //
  uintptr,          //
  float32,          //
  float64,          //
  complex64,        //
  complex128,       //

  string,           //
  rune,             //
  byte,             //

  boolean,          //

  pointer,          //
  struct,           //
  func,             //
  array,            //
  slice,            //
  map,              //
  channel,          //
  interface         //
}

// --- Flags ---
enum NodeFlag : uint32(bit_flags) {
  None,             // NOTE - Reserved
  NodeIndexed,      // NOTE - Reserved
  NodeBinary,       // NOTE - Reserved
  NodeUnary,        // NOTE - Reserved
}

enum ValueFlag : uint32(bit_flags) {
  None,         // NOTE - Reserved
  Pointer,      // NOTE - Reserved
  Quotation,
  IfConditon,
  IfBody,
  IfElse,

  FuncMeta,
  FuncParam,
  FuncBody,

  SwitchExp,
  SwitchBody,

  CaseExp,
  CaseBody,

  ForInit,
  ForCondition,
  ForPost,
  ForBody,

  ForRangeVar1,
  ForRangeVar2,
  ForRangeValue,

  DefaultBody,
}

struct StructField {
  name: uint32;         // String address
  type: uint32;         // TypeDef address
  misc: uint32;         // String address
}

table Type {
  // Pointer
  elem: uint32;         // TypeDef address

  // Interface
  methods: [uint64];    // Array of TypeDef & String addresses
                        // 0-32bits = TypeDef address
                        // 32-64bits = String address

  // Struct
  fields: [StructField];

  // Func
  params: [uint64];
  results: [uint64];
  method: uint64;

  // Map
  key: uint32;          // TypeDef address
  value: uint32;        // TypeDef address

  // Channel
  dir: bool;

  // Array
  size: uint64;          // For multi dimensional arrays, integer is split
}

table TypeDef {
  base: uint;           // Kind enum or pointer address of type
  id: uint;
  type: Type;
  flags: uint;
}

table TypeEntry {
  key: uint(key);
  value: TypeDef;
}

table App {
  nodes: [program.Node];           // Flat array of all nodes
  lut: [program.StringEntry];      // String lookup table
  types: [TypeEntry];              // Type registry
  name: string;
  schver: string;                  // Schema version
  wailsver: string;                // Version of wails
  version: string;                 // Version of the program
  flags: program.Flag;             // Program flags
}

root_type App;
